# Generated by Django 6.0.5 on 2026-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='123 Medical Arcade, Suite 400, Metropolis, NY 10001')),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('whatsapp', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('weekdays_working_hours', models.CharField(default='Mon - Fri: 8:00 AM - 6:00 PM', max_length=100)),
                ('saturday_working_hours', models.CharField(default='Sat: 9:00 AM - 2:00 PM', max_length=100)),
                ('sunday_working_hours', models.CharField(default='Sun: Closed', max_length=100)),
                ('map_link', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.6175407386008!2d-73.98782292346985!3d40.74844047138767!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c259a9b3117469%3A0xd134e199a405a163!2sEmpire%20State%20Building!5e0!3m2!1sen!2sus!4v1713374240000!5m2!1sen!2sus')),
                ('facebook_url', models.CharField(blank=True, default='https://facebook.com', max_length=255)),
                ('twitter_url', models.CharField(blank=True, default='https://twitter.com', max_length=255)),
                ('instagram_url', models.CharField(blank=True, default='https://instagram.com', max_length=255)),
                ('linkedin_url', models.CharField(blank=True, default='https://linkedin.com', max_length=255)),
                ('notification_method', models.CharField(choices=[('email', 'Email only'), ('whatsapp', 'WhatsApp only'), ('both', 'Both Email and WhatsApp')], default='both', max_length=15)),
            ],
            options={
                'verbose_name': 'Clinic Information',
                'verbose_name_plural': 'Clinic Information',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial', models.CharField(blank=True, help_text='Fallback avatar initials if image is missing', max_length=10)),
                ('stars', models.PositiveIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('quote', models.TextField()),
                ('delay', models.CharField(default='0.1s', help_text='CSS fade animation delay (e.g. 0.1s, 0.2s)', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Optional patient photo avatar', null=True, upload_to='patients/')),
            ],
        ),
    ]
