# Generated by Django 6.0.5 on 2026-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_remove_review_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicinformation',
            name='doctor_image',
            field=models.ImageField(blank=True, help_text='Profile image for the About section. Max 2 MB. Accepted: .jpg, .jpeg, .png, .webp', null=True, upload_to='doctor/'),
        ),
    ]
